version: '3.4'

services:
  project.base.example.webapi:
    image: ${DOCKER_REGISTRY-}projectbaseexamplewebapi
    build:
      context: .
      dockerfile: Project.Base.Example.WebApi/Dockerfile
    extra_hosts:
      - "DESKTOP-ISJ1TBU:192.168.1.9"
