using Project.Base.Domain.Object.Shared;
using Project.Base.Example.Enumerators;

namespace Project.Base.Example.Domain.Objects
{
    public class City : BaseObjectWithId
    {
        #region RULES
        public static readonly IDictionary<CountryEnum, string> POSTAL_CODE_PATTERN = new Dictionary<CountryEnum, string> {
            {CountryEnum.GB, "GIR[ ]?0AA|((AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}))|BFPO[ ]?\\d{1,4}"},
            {CountryEnum.JE, "JE\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}"},
            {CountryEnum.GG, "GY\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}"},
            {CountryEnum.IM, "IM\\d[\\dA-Z]?[ ]?\\d[ABD-HJLN-UW-Z]{2}"},
            {CountryEnum.US, "\\d{5}([ \\-]\\d{4})?"},
            {CountryEnum.CA, "[ABCEGHJKLMNPRSTVXY]\\d[ABCEGHJ-NPRSTV-Z][ ]?\\d[ABCEGHJ-NPRSTV-Z]\\d"},
            {CountryEnum.DE, "\\d{5}"},
            {CountryEnum.JP, "\\d{3}-\\d{4}"},
            {CountryEnum.FR, "\\d{2}[ ]?\\d{3}"},
            {CountryEnum.AU, "\\d{4}"},
            {CountryEnum.IT, "\\d{5}"},
            {CountryEnum.CH, "\\d{4}"},
            {CountryEnum.AT, "\\d{4}"},
            {CountryEnum.ES, "\\d{5}"},
            {CountryEnum.NL, "\\d{4}[ ]?[A-Z]{2}"},
            {CountryEnum.BE, "\\d{4}"},
            {CountryEnum.DK, "\\d{4}"},
            {CountryEnum.SE, "\\d{3}[ ]?\\d{2}"},
            {CountryEnum.NO, "\\d{4}"},
            {CountryEnum.BR, "\\d{5}[\\-]?\\d{3}"},
            {CountryEnum.PT, "\\d{4}([\\-]\\d{3})?"},
            {CountryEnum.FI, "\\d{5}"},
            {CountryEnum.AX, "22\\d{3}"},
            {CountryEnum.KR, "\\d{3}[\\-]\\d{3}"},
            {CountryEnum.CN, "\\d{6}"},
            {CountryEnum.TW, "\\d{3}(\\d{2})?"},
            {CountryEnum.SG, "\\d{6}"},
            {CountryEnum.DZ, "\\d{5}"},
            {CountryEnum.AD, "AD\\d{3}"},
            {CountryEnum.AR, "([A-HJ-NP-Z])?\\d{4}([A-Z]{3})?"},
            {CountryEnum.AM, "(37)?\\d{4}"},
            {CountryEnum.AZ, "\\d{4}"},
            {CountryEnum.BH, "((1[0-2]|[2-9])\\d{2})?"},
            {CountryEnum.BD, "\\d{4}"},
            {CountryEnum.BB, "(BB\\d{5})?"},
            {CountryEnum.BY, "\\d{6}"},
            {CountryEnum.BM, "[A-Z]{2}[ ]?[A-Z0-9]{2}"},
            {CountryEnum.BA, "\\d{5}"},
            {CountryEnum.IO, "BBND 1ZZ"},
            {CountryEnum.BN, "[A-Z]{2}[ ]?\\d{4}"},
            {CountryEnum.BG, "\\d{4}"},
            {CountryEnum.KH, "\\d{5}"},
            {CountryEnum.CV, "\\d{4}"},
            {CountryEnum.CL, "\\d{7}"},
            {CountryEnum.CR, "\\d{4,5}|\\d{3}-\\d{4}"},
            {CountryEnum.HR, "\\d{5}"},
            {CountryEnum.CY, "\\d{4}"},
            {CountryEnum.CZ, "\\d{3}[ ]?\\d{2}"},
            {CountryEnum.DO, "\\d{5}"},
            {CountryEnum.EC, "([A-Z]\\d{4}[A-Z]|(?:[A-Z]{2})?\\d{6})?"},
            {CountryEnum.EG, "\\d{5}"},
            {CountryEnum.EE, "\\d{5}"},
            {CountryEnum.FO, "\\d{3}"},
            {CountryEnum.GE, "\\d{4}"},
            {CountryEnum.GR, "\\d{3}[ ]?\\d{2}"},
            {CountryEnum.GL, "39\\d{2}"},
            {CountryEnum.GT, "\\d{5}"},
            {CountryEnum.HT, "\\d{4}"},
            {CountryEnum.HN, "(?:\\d{5})?"},
            {CountryEnum.HU, "\\d{4}"},
            {CountryEnum.IS, "\\d{3}"},
            {CountryEnum.IN, "\\d{6}"},
            {CountryEnum.ID, "\\d{5}"},
            {CountryEnum.IL, "\\d{5}"},
            {CountryEnum.JO, "\\d{5}"},
            {CountryEnum.KZ, "\\d{6}"},
            {CountryEnum.KE, "\\d{5}"},
            {CountryEnum.KW, "\\d{5}"},
            {CountryEnum.LA, "\\d{5}"},
            {CountryEnum.LV, "\\d{4}"},
            {CountryEnum.LB, "(\\d{4}([ ]?\\d{4})?)?"},
            {CountryEnum.LI, "(948[5-9])|(949[0-7])"},
            {CountryEnum.LT, "\\d{5}"},
            {CountryEnum.LU, "\\d{4}"},
            {CountryEnum.MK, "\\d{4}"},
            {CountryEnum.MY, "\\d{5}"},
            {CountryEnum.MV, "\\d{5}"},
            {CountryEnum.MT, "[A-Z]{3}[ ]?\\d{2,4}"},
            {CountryEnum.MU, "(\\d{3}[A-Z]{2}\\d{3})?"},
            {CountryEnum.MX, "\\d{5}"},
            {CountryEnum.MD, "\\d{4}"},
            {CountryEnum.MC, "980\\d{2}"},
            {CountryEnum.MA, "\\d{5}"},
            {CountryEnum.NP, "\\d{5}"},
            {CountryEnum.NZ, "\\d{4}"},
            {CountryEnum.NI, "((\\d{4}-)?\\d{3}-\\d{3}(-\\d{1})?)?"},
            {CountryEnum.NG, "(\\d{6})?"},
            {CountryEnum.OM, "(PC )?\\d{3}"},
            {CountryEnum.PK, "\\d{5}"},
            {CountryEnum.PY, "\\d{4}"},
            {CountryEnum.PH, "\\d{4}"},
            {CountryEnum.PL, "\\d{2}-\\d{3}"},
            {CountryEnum.PR, "00[679]\\d{2}([ \\-]\\d{4})?"},
            {CountryEnum.RO, "\\d{6}"},
            {CountryEnum.RU, "\\d{6}"},
            {CountryEnum.SM, "4789\\d"},
            {CountryEnum.SA, "\\d{5}"},
            {CountryEnum.SN, "\\d{5}"},
            {CountryEnum.SK, "\\d{3}[ ]?\\d{2}"},
            {CountryEnum.SI, "\\d{4}"},
            {CountryEnum.ZA, "\\d{4}"},
            {CountryEnum.LK, "\\d{5}"},
            {CountryEnum.TJ, "\\d{6}"},
            {CountryEnum.TH, "\\d{5}"},
            {CountryEnum.TN, "\\d{4}"},
            {CountryEnum.TR, "\\d{5}"},
            {CountryEnum.TM, "\\d{6}"},
            {CountryEnum.UA, "\\d{5}"},
            {CountryEnum.UY, "\\d{5}"},
            {CountryEnum.UZ, "\\d{6}"},
            {CountryEnum.VA, "00120"},
            {CountryEnum.VE, "\\d{4}"},
            {CountryEnum.ZM, "\\d{5}"},
            {CountryEnum.AS, "96799"},
            {CountryEnum.CC, "6799"},
            {CountryEnum.CK, "\\d{4}"},
            {CountryEnum.RS, "\\d{6}"},
            {CountryEnum.ME, "8\\d{4}"},
            {CountryEnum.CX, "6798"},
            {CountryEnum.ET, "\\d{4}"},
            {CountryEnum.FK, "FIQQ 1ZZ"},
            {CountryEnum.NF, "2899"},
            {CountryEnum.FM, "(9694[1-4])([ \\-]\\d{4})?"},
            {CountryEnum.GF, "9[78]3\\d{2}"},
            {CountryEnum.GN, "\\d{3}"},
            {CountryEnum.GP, "9[78][01]\\d{2}"},
            {CountryEnum.GS, "SIQQ 1ZZ"},
            {CountryEnum.GU, "969[123]\\d([ \\-]\\d{4})?"},
            {CountryEnum.GW, "\\d{4}"},
            {CountryEnum.HM, "\\d{4}"},
            {CountryEnum.IQ, "\\d{5}"},
            {CountryEnum.KG, "\\d{6}"},
            {CountryEnum.LR, "\\d{4}"},
            {CountryEnum.LS, "\\d{3}"},
            {CountryEnum.MG, "\\d{3}"},
            {CountryEnum.MH, "969[67]\\d([ \\-]\\d{4})?"},
            {CountryEnum.MN, "\\d{6}"},
            {CountryEnum.MP, "9695[012]([ \\-]\\d{4})?"},
            {CountryEnum.MQ, "9[78]2\\d{2}"},
            {CountryEnum.NC, "988\\d{2}"},
            {CountryEnum.NE, "\\d{4}"},
            {CountryEnum.VI, "008(([0-4]\\d)|(5[01]))([ \\-]\\d{4})?"},
            {CountryEnum.PF, "987\\d{2}"},
            {CountryEnum.PG, "\\d{3}"},
            {CountryEnum.PM, "9[78]5\\d{2}"},
            {CountryEnum.PN, "PCRN 1ZZ"},
            {CountryEnum.PW, "96940"},
            {CountryEnum.RE, "9[78]4\\d{2}"},
            {CountryEnum.SH, "(ASCN|STHL) 1ZZ"},
            {CountryEnum.SJ, "\\d{4}"},
            {CountryEnum.SO, "\\d{5}"},
            {CountryEnum.SZ, "[HLMS]\\d{3}"},
            {CountryEnum.TC, "TKCA 1ZZ"},
            {CountryEnum.WF, "986\\d{2}"},
            {CountryEnum.YT, "976\\d{2}"},
            {CountryEnum.OTHER, "\\d{5}"},
        };

        #endregion
        public string PostalCode { get; set; }

        public CountryEnum Country { get; set; }

        public string Name { get; set; }
    }
}
